import React from "react";
import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  Platform,
  Pressable,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { router } from "expo-router";
import { LinearGradient } from "expo-linear-gradient";
import { useThemeColors } from "@/constants/colors";

export default function TermsScreen() {
  const colors = useThemeColors();
  const insets = useSafeAreaInsets();
  const topPad = Platform.OS === "web" ? 67 : insets.top;
  const botPad = Platform.OS === "web" ? 34 : insets.bottom;

  return (
    <View style={{ flex: 1, backgroundColor: colors.background }}>
      <LinearGradient colors={["#1A0A0A", "#0D0D1A"]} style={StyleSheet.absoluteFill} />

      <View style={[styles.header, { paddingTop: topPad + 8, borderBottomColor: colors.border }]}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={colors.text} />
        </Pressable>
        <Text style={[styles.headerTitle, { color: colors.text }]}>Terms & Conditions</Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView
        contentContainerStyle={[styles.content, { paddingBottom: botPad + 32 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.updated, { color: colors.textMuted }]}>Last updated: April 2025</Text>

        <Section title="1. Acceptance of Terms" colors={colors}>
          By downloading, installing, or using PokeScan TCG ("the App"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the App.
        </Section>

        <Section title="2. Eligibility" colors={colors}>
          You must be at least 13 years of age to use PokeScan TCG. By using the App, you represent and warrant that you meet this requirement. Users under 18 should review these terms with a parent or guardian.
        </Section>

        <Section title="3. Account Responsibility" colors={colors}>
          You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorised use of your account.{"\n\n"}
          You must provide accurate and complete information when creating your account. Impersonating another person or using a misleading username is prohibited.
        </Section>

        <Section title="4. Acceptable Use" colors={colors}>
          You agree not to use the App to:{"\n\n"}
          • Post, share, or transmit any content that is unlawful, offensive, threatening, abusive, harassing, or defamatory{"\n"}
          • Violate the intellectual property rights of others{"\n"}
          • Spam, scam, or defraud other users in the marketplace{"\n"}
          • Attempt to gain unauthorised access to our systems or other users' accounts{"\n"}
          • Use automated tools or bots to scrape or interact with the App{"\n"}
          • Misrepresent card conditions or grades in marketplace listings{"\n"}
          • Engage in any activity that disrupts or interferes with the App
        </Section>

        <Section title="5. Marketplace & Trades" colors={colors}>
          PokeScan TCG provides a platform for users to list cards for sale or trade. We are not a party to any transaction between users and are not responsible for the quality, safety, legality, or availability of listed items.{"\n\n"}
          Users are solely responsible for ensuring their listings are accurate and honest. Any disputes between buyers and sellers are the sole responsibility of the parties involved.
        </Section>

        <Section title="6. Premium Subscription" colors={colors}>
          PokeScan TCG offers a Premium subscription with additional features. By subscribing, you agree to pay the applicable fees. Subscriptions auto-renew unless cancelled before the renewal date.{"\n\n"}
          Refunds are handled in accordance with the App Store or Google Play refund policies. We do not offer refunds directly for subscription fees except where required by law.
        </Section>

        <Section title="7. AI Card Scanning & Grading" colors={colors}>
          The AI-powered card scanning and grading features are provided as a guide only. Grades and valuations generated by the App are estimates and should not be relied upon as professional appraisals. We make no warranty as to the accuracy of AI-generated results.
        </Section>

        <Section title="8. Intellectual Property" colors={colors}>
          Pokémon and all related names, characters, and imagery are trademarks of Nintendo, Game Freak, and The Pokémon Company. PokeScan TCG is an independent fan tool and is not affiliated with, endorsed by, or connected to these companies.{"\n\n"}
          All original content within the App — including its design, code, and branding — is owned by PokeScan TCG and may not be reproduced without permission.
        </Section>

        <Section title="9. Disclaimer of Warranties" colors={colors}>
          The App is provided on an "as is" and "as available" basis without warranties of any kind, either express or implied. We do not warrant that the App will be uninterrupted, error-free, or free of viruses or other harmful components.
        </Section>

        <Section title="10. Limitation of Liability" colors={colors}>
          To the fullest extent permitted by law, PokeScan TCG shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the App, even if we have been advised of the possibility of such damages.
        </Section>

        <Section title="11. Termination" colors={colors}>
          We reserve the right to suspend or terminate your account at our sole discretion if you violate these Terms, engage in fraudulent activity, or cause harm to other users or the platform.
        </Section>

        <Section title="12. Changes to These Terms" colors={colors}>
          We may update these Terms from time to time. We will notify you of significant changes via email or an in-app notification. Continued use of the App after changes constitutes acceptance of the updated Terms.
        </Section>

        <Section title="13. Governing Law" colors={colors}>
          These Terms are governed by the laws of England and Wales. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </Section>

        <Section title="14. Contact Us" colors={colors}>
          If you have any questions about these Terms, please contact us at:{"\n\n"}
          Email: pokescantcg@gmail.com
        </Section>
      </ScrollView>
    </View>
  );
}

function Section({ title, children, colors }: { title: string; children: React.ReactNode; colors: any }) {
  return (
    <View style={styles.section}>
      <Text style={[styles.sectionTitle, { color: colors.text }]}>{title}</Text>
      <Text style={[styles.sectionBody, { color: colors.textSecondary }]}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontFamily: "Outfit_600SemiBold",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  updated: {
    fontSize: 12,
    fontFamily: "Outfit_400Regular",
    marginBottom: 24,
    textAlign: "center",
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: "Outfit_700Bold",
    marginBottom: 8,
  },
  sectionBody: {
    fontSize: 14,
    fontFamily: "Outfit_400Regular",
    lineHeight: 22,
  },
});
